### ISSUE TITLE
Being prompted for email verification code before MFA code causing "NoSuchElementException"

### ISSUE THREAD

**Issue by ScottG489** [mintapi/mintapi#254]
I've started getting prompted for an email verification code before the MFA code. I'm using the `soft-token` method with mintapi and it's been working for a while. I have my Intuit account set up to only require the soft-token, so I imagine they must have added additional security measures more recently.

If I use Chrome manually, I'm only seeing this when I log in with incognito. I'm also seeing a captcha in incognito, however I don't see that in chrome when running head-fully with mintapi.

I know there is an `email` MFA method. However, I'm not sure if it's allowed to be used with another MFA method (since I'd need two). I tried using both methods or only the `email` method to see if I could at least get past that part, but any combination of the methods always results in the same error message:

> `selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-sign-in-mfa-password-collection-current-password"]"}`

Is anyone else experiencing this and is there a way I can get around it? Thanks for all your hard work on this library.

**Comment by Patrawr** [comment]
Looks like it's been solved with #262. Works for me with version 1.49.

**Comment by dcastillo84** [comment]
@ScottG489  were you able to get this to work, i am getting the same thing. MFA worked before but now its asking for an email auth code before that.

**Comment by ScottG489** [comment]
@dcastillo84 Was this issue still reproducing after you updated to a version after https://github.com/mrooney/mintapi/pull/262?

I haven't had a chance to retry in a while and it might be a few weeks until I'll be able to find some time to.

**Comment by dcastillo84** [comment]
@ScottG489 taking out session-path seemed to fix it for me. I did also update to the latest mintapi so that could have been a contributor as well.

**Comment by ScottG489** [comment]
@dcastillo84 Ok cool, good to know.

Though, when you say you took out `session-path`, do you mean that you were using the `session-path` argument before but are no longer now?

**Comment by dcastillo84** [comment]
@ScottG489 that is correct was using it before and no longer now

**Comment by jaron-l** [comment]
This is a bug/change in workflow for mint.com. Mintapi does not currently handle email mfa if soft-token is specified, see [here](https://github.com/mrooney/mintapi/blob/d5f6790400f13f9ba756e1b7048a8050c6b29039/mintapi/api.py#L360).

If anyone is ambitious, it might be worth creating a more dynamic sign in workflow that doesn't follow a line of try-excepts, but rather identifies prompt types and responds with the correct method.

**Comment by burkematthew** [comment]
@jaron-l do any of your latest changes to the sign in flow relate to this issue?

**Comment by jaron-l** [comment]
Not that has been merged into main. I have a dynamic sign in workflow working on a local branch on my computer but am breaking up the changes I made into multiple merge requests so as to not overwhelm. I'm hoping the dynamic sign in will address many of the sign issues we have open right now.
