### ISSUE TITLE
Login to Mint failed due to timeout in the Multifactor Method Loop

### ISSUE THREAD

**Issue by pazwicker** [mintapi/mintapi#515]
**Describe the bug**
Unable to log in to Mint. Last logged in yesterday via mintapi with no issues.

What version of MintAPI are you using? 2.5
What command[s] did you run / steps to reproduce?

```python
mint = mintapi.Mint(
        "email",  # Email used to log in to Mint
        "password",  # Your password used to log in to mint
        mfa_method="soft-token",  # Can be 'sms' (default) or 'email'.
        headless=True,  # Whether the chromedriver should work without opening a
        mfa_input_callback=None,
        mfa_token="mfa token",
        session_path=None,
        wait_for_sync=False,  # do not wait for accounts to sync
        wait_for_sync_timeout=1,  # number of seconds to wait for sync
        beta=True,
    )
```

Stacktrace/error received:

```
Login to Mint failed due to timeout in the Multifactor Method Loop
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_1/lib/python3.9/site-packages/mintapi/signIn.py", line 399, in sign_in
    WebDriverWait(driver, 5).until(
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_1/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_1/lib/python3.9/site-packages/mintapi/api.py", line 169, in login_and_get_token
    self.status_message = sign_in(
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_1/lib/python3.9/site-packages/mintapi/signIn.py", line 405, in sign_in
    raise RuntimeError(
RuntimeError: Login to Mint failed due to timeout in the Multifactor Method Loop
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_1/lib/python3.9/site-packages/mintapi/signIn.py", line 399, in sign_in
    WebDriverWait(driver, 5).until(
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_1/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_1/lib/python3.9/site-packages/mintapi/api.py", line 169, in login_and_get_token
    self.status_message = sign_in(
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_1/lib/python3.9/site-packages/mintapi/signIn.py", line 405, in sign_in
    raise RuntimeError(
RuntimeError: Login to Mint failed due to timeout in the Multifactor Method Loop

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "file_path", line 24, in <module>
    mint_data.main(connection_type)
  File "file_path", line 548, in main
    mint = mint_connect()
  File "file_path", line 39, in mint_connect
    mint = mintapi.Mint(
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_1/lib/python3.9/site-packages/mintapi/api.py", line 96, in __init__
    self.login_and_get_token(
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_1/lib/python3.9/site-packages/mintapi/api.py", line 191, in login_and_get_token
    raise Exception(msg) from e
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?redirect_url=https%3A%2F%2Fbeta.mint.intuit.com%2Foverview&offering_id=Intuit.ifs.mint&namespace_id=50000026&appfabric=true

```

**What did you expect to happen?**
Expected sign in to work

**What actually happened?**
Sign in did not work

**Additional context**
Running fine hourly via cron job up until today. Sometimes I've had success running with `headless=False` which sometimes just works, but this time the script still fails.

**Comment by ujjwalkrishna** [comment]
Getting the same error

**Comment by ianvanhoven** [comment]
Same error, starting today

**Comment by burkematthew** [comment]
Can everyone try again from the latest on main?

**Comment by hudcap** [comment]
@burkematthew thank you! I can confirm that the new `id` you added works!
Finally got around to working on #484 and was hitting this error, but once I pulled your changes, it went back to working.

**Comment by pazwicker** [comment]
That fix seemed to do it. All is working as expected. Thank you!

**Comment by dzg** [comment]
Sorry, which fix fixed? What does 'try again from the latest on main' mean?

**Comment by hudcap** [comment]
The fix was committed to the 'main' branch on github.
I'm guessing from your question that you installed mintapi using pip, which hasn't been updated yet.
Guessing also that you don't have git installed on your computer.
Try this to update to the latest on main:
```
pip install https://github.com/mintapi/mintapi/archive/main.zip
```

**Comment by dzg** [comment]
> The fix was committed to the 'main' branch on github. I'm guessing from your question that you installed mintapi using pip, which hasn't been updated yet. Guessing also that you don't have git installed on your computer. Try this to update to the latest on main:
> 
> ```
> pip install https://github.com/mintapi/mintapi/archive/main.zip
> ```
I do have `git` ... and yes I installed via `pip`.
I tried your suggested command, but it's still stopping at the password prompt. 
Thanks for your help

**Comment by emann3** [comment]
i tried using main (as noted above) and am still getting the error: Login to Mint failed due to timeout in the Multifactor Method Loop

it is on the page to select from my 2 accounts when it gets stuck

Command:
mintapi -f today --session-path --accounts user pass

StackTrace:
DevTools listening on ws://127.0.0.1:61673/devtools/browser/cd264ec6-088a-4814-9b82-1fdeafa6c948
[31588:32096:0714/160536.381:ERROR:device_event_log_impl.cc(214)] [16:05:36.369] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
Please enter your 6-digit MFA code: 993500
Login to Mint failed due to timeout in the Multifactor Method Loop
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 399, in sign_in
    WebDriverWait(driver, 5).until(
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 169, in login_and_get_token
    self.status_message = sign_in(
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 405, in sign_in
    raise RuntimeError(
RuntimeError: Login to Mint failed due to timeout in the Multifactor Method Loop
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 399, in sign_in
    WebDriverWait(driver, 5).until(
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 169, in login_and_get_token
    self.status_message = sign_in(
  File "C:\Python310\lib\site-packages\mintapi\signIn.py", line 405, in sign_in
    raise RuntimeError(
RuntimeError: Login to Mint failed due to timeout in the Multifactor Method Loop

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\Scripts\mintapi-script.py", line 33, in <module>
    sys.exit(load_entry_point('mintapi==2.5', 'console_scripts', 'mintapi')())
  File "C:\Python310\lib\site-packages\mintapi\cli.py", line 417, in main
    mint = Mint(
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 96, in __init__
    self.login_and_get_token(
  File "C:\Python310\lib\site-packages\mintapi\api.py", line 191, in login_and_get_token
    raise Exception(msg) from e
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3Db3838cad-9fde-4651-ab18-1308741f0759

**Comment by mrooney** [comment]
Yes, this is perhaps fixed by #516 which is now merged to `main`. I'll get a release out shortly as 2.6 so it's easier to have!

**Comment by ianvanhoven** [comment]
Ah, thx. I upgraded to 2.5 but didn't see the fix, so hand-patched
signOn.py myself :)
